import random
import time
#
#
def role(): 
    print("Добро пожаловать в королевство")
    time.sleep(3)
    print("Выберите роль:")
    time.sleep(1)
    print("1.Рыцарь\n2.Король")
#Рыцарь
def Rpred1():
    print("Вы стали рыцарем великого королевства")
    time.sleep(3)
    print("Много учась и работая вы достигли чина полководца")
    time.sleep(3)
    print("Вам поручен один из полков великой армии")
    time.sleep(3)
    print("...")
    time.sleep(3)
    print("На королевство собираются нападать орки")
    time.sleep(3)
    print("Король ожидает достойного отпора")
    time.sleep(3)
    print("Выберите действия в бою")
    time.sleep(3)
    print("1.Агресивная тактика\n2.Тактика главнокомандуещего")
    time.sleep(3) 
def R1Bagrm():
    print("Вы атаковали войска орков")
    time.sleep(3)
    print("Увы они оказались сильнее")
    time.sleep(3)        
    print("Вы невовремя проявили свою агрессию")
    time.sleep(3)
    print("Ваше войска разбито, а вы погибли")
    time.sleep(3)
    print("Это нанесло урон по всей армии")
    time.sleep(3)
    print("Game Over!")
def R1Bagrp():
    print("Вы атаковали войска орков")
    time.sleep(1)
    print("Ваша агрессия оказалась очень кстати")
    time.sleep(3)
    print("Вам попалось войско неопытных орков ")
    time.sleep(3)
    print("Вы с легкастью одалели их")
    time.sleep(3)
    print("Бой выигран")
    time.sleep(3)
    print("Поздравляю вас!")
    time.sleep(3)
    print("Вы успешно прошли боевое крещение")
def R2Btakt():
    time.sleep(1)
    print("Вы атаковали войска орков")
    time.sleep(3)
    print("Вы отлично управляете полком")
    time.sleep(3)
    print("Тактика оказалась действующей")
    time.sleep(3)
    print("Ваше королевство победило орков")
    time.sleep(3)
    print("Орки отступили")
    time.sleep(3)
    print("Поздравляю вас!")
    time.sleep(3)
    print("Вы успешно прошли боевое крещение")
###
def Rpred2():
    print("Нынешний полководец состарился\n и хочет провести последнии года в спокойствии") 
    time.sleep(3)
    print("За вашу смелость вы назначены на его пост")
    time.sleep(3)
    print("Теперь вы руководите всей армией королевства")  
    time.sleep(3)
    print("Король очень надеется на вас")
    time.sleep(3)
    print("...")
    time.sleep(3)
    print("Орки не смогли выдержать поражение")
    time.sleep(3)
    print("Они снова обьявляют войну")
    time.sleep(3)
    print("Король выбирает между войной и миром")
    time.sleep(3)
    print("Вы можете советоваться с королём")
    time.sleep(3)
    print("1.Согласиться с войной\n2.Обьявить переговоры")       
def Rpereg():
    print("Переговоры прошли успешно")
    time.sleep(3)
    print("Вы договрились по некоторым аспектам с орками")
    time.sleep(3)
    print("Они передумали обьявлять войну")
    time.sleep(3)
    print("Вы оказывается еще и отличный политик")
    time.sleep(3)
    print("Король хвалит вас")
def Rwar1():
    print("Вы решаете объявить войну")
    time.sleep(3)
    print("Вы с войском отправляетесь к границам государства")
    time.sleep(3)
    print("Пора принять первый бой")
    time.sleep(3)
    print("Выберите тактику")
    time.sleep(3)
    print("1.Тактика котла(окружение) 2.Динамичная атака 3.Стрела")
def Rtaktp(): #Тактика+(Котел и ДА)
    print("Тактика оказалась действующей")
    time.sleep(3)
    print("Вы успешно атаковали орков")
    time.sleep(3)
    print("Вы победили!")
    time.sleep(3)
    print("Орки отступили")
    time.sleep(3)
    print("Поздравляю вас")
def Rtaktm(): #Тактика стрела
    print("Вы атаковали орков")
    time.sleep(3)
    print("Тактика оказалась безуспешной")
    time.sleep(3)
    print("Вы потеряли много солдат")
    time.sleep(3)
    print("Вам пришлось отступать")
    time.sleep(3)
    print("...")
    time.sleep(3)
    print("Орки догнали вас и добили окончательно")
    time.sleep(3)
    print("Вы погибли")
    time.sleep(3)
    print("Game over!")
###
def Rpred3():
    print("После вашего сражения орки отступили")
    time.sleep(3)
    print("Позже произошло ещё несколько сражений")
    time.sleep(3)
    print("В итоге вы выиграли войну")
    time.sleep(3)
    print("...")
    time.sleep(3)
    print("Не стоило расслабляться...")
    time.sleep(3)
    print("Игра ещё не окончена")
    time.sleep(3)
    print("Орки неугомонные")
    time.sleep(3)
    print("Они собираются мстить")
    time.sleep(3)
    print("Приготовтесь дать последнее сражение")
    time.sleep(3)
    print("Выберите татику")
    time.sleep(3)
    print("1.Тактика котла(окружение) 2.Динамичная атака")
def Rbtlp():
    print("Вы атаковали орков")
    time.sleep(3)
    print("И атаковали успешно")
    time.sleep(3)
    print("Орки почуствовали ваще могущество")
    time.sleep(3)
    print("Они бегут")
    time.sleep(3)
    print("Теперь они точто не прийдут на ваши земли")
    time.sleep(3)
    print("В королевстве большой праздник")
    time.sleep(3)
    print("Вы стали героем!") 
def Rbtlm():
    print("Вы атаковали орков")
    time.sleep(3)
    print("Но эта тактика не прошла с ними второй раз")
    time.sleep(3)
    print("Они были готовы")
    time.sleep(3)
    print("Увы вы проиграли")
    time.sleep(3)
    print("Game over!")
###
def Rend():
    time.sleep(1.5)
    print("Вы стали поистине легендой")
    time.sleep(3)
    print("Вы победили во всех сражениях")
    time.sleep(3)
    print("Родина вам благодарна")
    time.sleep(3)
    print("Вы прошли игру!")
    time.sleep(1.5)
    print("Game End!")
#
#
#Король
def Kpred():
    time.sleep(3)    
    print("Hello world!")
    time.sleep(3)
    print("Ладно это не всё")
    time.sleep(1.5)
    print("...")
    time.sleep(1.5)
    print("Вам очень повезло")
    time.sleep(3)
    print("Вы родились наследником короля")
    time.sleep(3)
    print("Ну очень большого королевства")
    time.sleep(3)
    print("...")
    time.sleep(3)
    print("Шли годы")
    time.sleep(3)
    print("Вы выросли")
    time.sleep(3)
    print("Пора становиться королём")
    time.sleep(1.5)
    print("...")

    time.sleep(1.5)    
    print("Вы стали королём")
    time.sleep(3)
    print("Да здравствует",OneName)
    time.sleep(3)
    print("К сожалению ваш отец скончался")
    time.sleep(3)
    print("Он был великим королём")
    time.sleep(3)
    print("Надеюсь он оставил хорошего наследника")
    time.sleep(3)
    print("Это мы сейчас и проверим")
    time.sleep(1.5)
    print("...")
    time.sleep(1.5)

    print("Вам надо решить несколько вопросов")
    time.sleep(3)
    print("Помошники предложили принять несколько законов")
    time.sleep(3)
    print("Чтож начнём")
def Kz1():
    time.sleep(3)
    print("Первый закон предусматревает поддержку купцов вашего королевства")
    time.sleep(3)
    print("Для этого надо увеличить таможенные сборы")
    time.sleep(3)
    print("Выбирайте:")
    time.sleep(3)
    print("1.Принять закон\n2.Отказаться от принятия")
def Kz2():
    time.sleep(3)
    print("Следующий закон")
    time.sleep(3)
    print("Надо понизить уровень бедности")
    time.sleep(3)
    print("Для этого построим несколько государственных ферм")
    time.sleep(3)
    print("Бедняки будут на них работать")
    time.sleep(3)
    print("Приносить 50% урожая вам, остальное забирать себе")
    time.sleep(3)
    print("Выдадим также каждому по участку земли")
    time.sleep(3)
    print("Выбирайте:")
    time.sleep(3)
    print("1.Принять закон\n2.Отказаться от принятия")
def Kz3():
    time.sleep(3)
    print("Ещё один закон предусматривает постройку школ")
    time.sleep(3)
    print("Детям надо где-то учиться")
    time.sleep(3)
    print("А то уровень грамотности падает из года в год")
    time.sleep(3)
    print("Но на это прийдётся выделять много средств")
    time.sleep(3)
    print("Так что надо всё обдумать")
    time.sleep(1.5)
    print("...")
    time.sleep(1.5)
    print("Выбирайте:")
    time.sleep(3)
    print("1.Принять закон\n2.Отказаться от принятия")
def Kzp():
    time.sleep(3) 
    print("Жители довольны вашим решением")
    time.sleep(3) 
    print("Они рады таким поправкам")
    time.sleep(3) 
    print("Вы отлично действуете") 
    r1=r1+1 
def Kzm():
    time.sleep(3) 
    print("Жители недавольны вашим решением")
    time.sleep(3) 
    print("Ваши советники также обеспокоены")
    time.sleep(3) 
    print("Вы неверно поступили")
###
def Kdaugh():
    time.sleep(3) 
    print("Есть относительно хорошие новости")
    time.sleep(3) 
    print("У вас есть дочь") 
    time.sleep(3) 
    print("А королю из соседнего корллевства она понравилась")
    time.sleep(3) 
    print("И он хочет жениться на ней")
    time.sleep(3) 
    print("Он просит руки и сердца ")
    time.sleep(3) 
    print("Вы на правах отца должны вынести решение") 
    time.sleep(3) 
    print("Хорошо обдумайте это решение") 
    time.sleep(3) 
    print("1.Согласиться на свадьбу 2.Не соглашаться")    
def Kdaughp():
    time.sleep(3) 
    print("Вы согласились выдать дочь замуж")
    time.sleep(3) 
    print("Король соседнего государства рад вашему решению")
    time.sleep(3) 
    print("Дипломатические отношения с соседним государством улучшились") 
def Kdaughm():
    time.sleep(3) 
    print("Король соеднего государства разгневан") 
    time.sleep(3) 
    print("Его огорчило ваше решение")
    time.sleep(3) 
    print("Он все ещё хочет заполучить вашу дочь")
    time.sleep(3) 
    print("Он объявляет вам войну")
###
def Kprwar():
    time.sleep(3) 
    print("И так")
    time.sleep(3) 
    print("Вам объявили войну")
    time.sleep(3) 
    print("Прийдется принять несколько боёв")
    time.sleep(3) 
    print("Победив войне вы защитите свою дочь")
    time.sleep(3) 
    print("Да прибудет с вами сила")
def Kbatl1():   
    time.sleep(3) 
    print("Да начнется бой великий")
    time.sleep(3) 
    print("Бейтесь рыцари великие за родину")
    time.sleep(3) 
    print("За королевство")
    time.sleep(3) 
    print("За короля")
    time.sleep(3) 
    print("Выберите тактику:")
    time.sleep(3) 
    print("1.Тактика котла(окружение) 2.Динамичная атака 3.Стрела")
def Kbatl2():
    time.sleep(3) 
    print("Вы принимаете второй бой")
    time.sleep(3) 
    print("Не посрамите родину")
    time.sleep(3) 
    print("Защищайте родину")
    time.sleep(3) 
    print("Выберите тактику:")
    time.sleep(3) 
    print("1.Тактика котла(окружение) 2.Динамичная атака 3.Стрела")
def Kbatl3():
    time.sleep(3) 
    print("Пора последней битвы")
    time.sleep(3) 
    print("Она будет Великой")
    time.sleep(3) 
    print("Великой битвой государств")
    time.sleep(3) 
    print("Выберите тактику:")
    time.sleep(3) 
    print("1.Тактика котла(окружение) 2.Динамичная атака 3.Стрела")
def Ktaktp():
    time.sleep(3) 
    print("Вы атковали врага")
    time.sleep(3) 
    print("Вы доминируете над ним")
    time.sleep(3) 
    print("Войска противника становятся меньше")
    time.sleep(3) 
    print("Всё!")
    time.sleep(3) 
    print("Вы одержали победу")
    time.sleep(3) 
    print("Слава Армии Великого королевства!")
    r2=r2+1
def Ktaktm():
    time.sleep(3) 
    print("Вы атаковали врага")
    time.sleep(3) 
    print("О нет!")
    time.sleep(3) 
    print("Кажется вы проигрываете")
    time.sleep(3) 
    print("Враг доминирует")
    time.sleep(3) 
    print("Вас становится меньше")
    time.sleep(3) 
    print("Увы, но вы проиграли")
    time.sleep(3) 
    print("Вам приходится отступать")
###
def Kk1():
    time.sleep(3) 
    print("Вы были плохим королём") 
    time.sleep(3) 
    print("Вы плохо провели войну")
    time.sleep(3) 
    print("И отвратительно провели реформы")
    time.sleep(3) 
    print("Вы отчаялись и покинули пост короля")
    time.sleep(3) 
    print("Народ не будет вас вспоминать")
    time.sleep(3) 
    print("Game over !")
def Kk2():
    time.sleep(3) 
    print("Вы были относительно хорошим королём") 
    time.sleep(3) 
    print("Вы плохо провели войну")
    time.sleep(3) 
    print("Относительно хорошо провели реформы")
    time.sleep(3) 
    print("Вами недовольны и вас отставили")
    time.sleep(3) 
    print("Народ врядли вас похвалит")
    time.sleep(3) 
    print("Game over !")
def Kk3():
    time.sleep(3) 
    print("Вы были вполне хорошим королём") 
    time.sleep(3) 
    print("Вы плохо провели войну")
    time.sleep(3) 
    print("Зато отлично провели реформы")
    time.sleep(3) 
    print("Вы до старости остались на престоле, позже вас сменил сын")
    time.sleep(3) 
    print("Вас похвалил народ")
    time.sleep(3) 
    print("Game end !")
def Kk4():
    time.sleep(3) 
    print("Вы были относительно хорошим королём") 
    time.sleep(3) 
    print("Вы хорошо провели войну")
    time.sleep(3) 
    print("Но отвратительно провели реформы")
    time.sleep(3) 
    print("Вы ушли в отставку")
    time.sleep(3) 
    print("Народ вас врядли вспомнит")
    time.sleep(3) 
    print("Game over !")
def Kk5():
    time.sleep(3) 
    print("Вы были неплохим королём") 
    time.sleep(3) 
    print("Вы хорошо провели войну")
    time.sleep(3) 
    print("И хорошо провели реформы")
    time.sleep(3) 
    print("Вы остались в почёте")
    time.sleep(3) 
    print("Народ вас будет долго вспоминать")
    time.sleep(3) 
    print("Game end !")
def Kk6():
    time.sleep(3) 
    print("Вы были хорошим королём") 
    time.sleep(3) 
    print("Вы хорошо провели войну")
    time.sleep(3) 
    print("И отлично провели реформы")
    time.sleep(3) 
    print("Вы отлично правили")
    time.sleep(3) 
    print("Вы остались в истории государства отличным королём")
    time.sleep(3) 
    print("Game end !")  
def Kk7():
    time.sleep(3) 
    print("Вы были вполне хорошим королём") 
    time.sleep(3) 
    print("Вы отлично провели войну")
    time.sleep(3) 
    print("Но плохо провели реформы")
    time.sleep(3) 
    print("Вы до старости остались на престоле, позже вас сменил сын")
    time.sleep(3) 
    print("Вас похвалил народ")
    time.sleep(3) 
    print("Game end !")
def Kk8():
    time.sleep(3) 
    print("Вы были хорошим королём") 
    time.sleep(3) 
    print("Вы отлично провели войну")
    time.sleep(3) 
    print("И хорошо провели реформы")
    time.sleep(3) 
    print("Вы отлично правили")
    time.sleep(3) 
    print("Вы остались в истории государства отличным королём")
    time.sleep(3) 
    print("Game end !")
def Kk9():
    time.sleep(3) 
    print("Вы были замечательным королём") 
    time.sleep(3) 
    print("Вы великолепно провели войну")
    time.sleep(3) 
    print("И отлично провели реформы")
    time.sleep(3) 
    print("Вы по праву вошли в историю как великий король")
    time.sleep(3) 
    print("Слава королю", OneName)
    time.sleep(3) 
    print("Game end !")
###
def Kkonz():
    if r1<=1 and r2<=1:
        Kk1()
    elif r1==2 and r2<=1:
        Kk2()
    elif r1==3 and r2<=1:
        Kk3()
    elif r1<=1 and r2==2:
        Kk4()
    elif r1==2 and r2==2:
        Kk5()
    elif r1==3 and r2==2:
        Kk6()
    elif r1<=1 and r2==3:
        Kk7()
    elif r1==2 and r2==3:
        Kk8()
    elif r1==3 and r2==3:
        Kk9()
    
    

#Рандомайзер имён
FirstName=["Премудрый","Великий","Могучий","Ярый","Злой","Мощный"]
Name=[" Ярослав"," Святорус"," Изяслав","Эдвард", "Гордон","Эльбрус","Генри","Олег"]
fn=random.randint(0,5)
n=random.randint(0,7)
firstname=FirstName[fn]
name=Name[n]
OneName=firstname+name  
r1=0 
r2=0 
###

role() #Выбор роли
role=input()
if role=="1": #Роль рыцаря
    Rpred1()
    battle=input()
    
    if battle=="1":
        a=random.randint(0,1)
        if a==0:
            R1Bagrm()
            exit()
        elif a==1:
            R1Bagrp()    
    elif battle=="2":
        R2Btakt()        

    Rpred2()
    vim=input()
    if vim=="1":
        Rwar1()
        takt1=input()
        if takt1=="2" or "3":
            Rtaktp()
        elif takt1=="1":
            Rtaktm() 
            exit()
    elif vim=="2":
        Rpereg()
    Rpred3()
    takt2=input()
    if takt2==takt1:
        Rbtlm()
        exit()
    elif takt2!=takt1:
        Rbtlp()
    Rend()

elif role=="2": #Роль короля
    Kpred()
    
    Kz1()
    z1=input()
    if z1=="1":
        Kzp()
    elif z1=="2":
        Kzm()  
    Kz2()
    z2=input()
    if z2=="1":
        Kzp()
    elif z2=="2":
        Kzm() 
    Kz3()
    z3=input()
    if z3=="1":
        Kzp()
    elif z3=="2":
        Kzm() 
    
    Kdaugh()
    vibor=input()
    if vibor=="1":
        Kdaughp()
    elif vibor=="2":
        Kdaughm()

        Kprwar()
        
        Kbatl1()
        t1=input()
        if t1=="1" or "2":
            Ktaktp()
        elif t1 == "3":
            Ktaktm()
        
        Kbatl2()
        t2=input()
        if t2=="2" or "3":
            Ktaktp()
        elif t2 == "1":
            Ktaktm()
        
        Kbatl3()
        t3=input()
        if t1=="1" or "3":
            Ktaktp()
        elif t1 == "2":
            Ktaktm()
    Kkonz()
else: print("Error")
